export const ONBOARDING_SLIDES = [
  {
    id: 1,
    title: 'Bem-vinda ao\nGestar com Trombofilia',
    subtitle: 'Um espaço criado com amor para mulheres que enfrentam a trombofilia na jornada gestacional.',
    image: require('@/assets/images/icon.png'),
    bg: '#FDF8F5',
  },
  {
    id: 2,
    title: 'Você não está\nsozinha nessa jornada',
    subtitle: 'Aqui você encontra suporte, educação, organização e uma comunidade que entende o que você vive.',
    image: require('@/assets/images/icon.png'),
    bg: '#FFF0F3',
  },
  {
    id: 3,
    title: 'Sua saúde,\nsua história, seu cuidado',
    subtitle: 'Gerencie sua gestação, acompanhe seus exames, receba lembretes e acesse guias especializados.',
    image: require('@/assets/images/icon.png'),
    bg: '#F5F0FF',
  },
];

export const PROFILE_TYPES = [
  { id: 'tentante', label: 'Tentante', icon: '🌸', description: 'Estou tentando engravidar' },
  { id: 'gestante', label: 'Gestante', icon: '🤰', description: 'Estou grávida' },
  { id: 'fiv', label: 'FIV / Reprodução Assistida', icon: '🔬', description: 'Estou em tratamento de FIV' },
  { id: 'investigacao', label: 'Em Investigação', icon: '🔍', description: 'Investigando trombofilia' },
  { id: 'pos_perda', label: 'Pós-perda Gestacional', icon: '🕊️', description: 'Tive perdas gestacionais' },
  { id: 'acompanhamento', label: 'Paciente da Consultoria', icon: '💜', description: 'Sou paciente da consultoria' },
];

export const GUIDES = [
  {
    id: 'exames',
    title: 'Entender seus Exames',
    subtitle: 'Compreenda os resultados dos seus exames laboratoriais',
    icon: '🧪',
    color: '#C9748F',
    premium: false,
    content: `## Guia para Entender seus Exames\n\nA trombofilia é diagnosticada por meio de uma série de exames laboratoriais específicos. Entender esses resultados é fundamental para o acompanhamento adequado da sua saúde gestacional.\n\n### Principais Exames\n\n**Anticoagulante Lúpico (LA)** — Detecta anticorpos que aumentam o risco de trombose. Resultado positivo em duas ocasiões com intervalo de 12 semanas confirma a síndrome antifosfolípide.\n\n**Anticorpos Anticardiolipina (aCL)** — IgG e IgM. Títulos acima de 40 GPL/MPL ou acima do percentil 99 são considerados positivos.\n\n**Anti-beta2-glicoproteína I** — Anticorpo importante para diagnóstico da SAF. Deve ser confirmado em duas dosagens com intervalo de 12 semanas.\n\n**Fator V de Leiden** — Mutação genética que aumenta o risco de trombose venosa. Pode ser heterozigota ou homozigota.\n\n**Mutação da Protrombina G20210A** — Aumenta os níveis de protrombina e o risco de trombose.\n\n**Deficiência de Proteína C, S e Antitrombina** — Proteínas naturais anticoagulantes. Deficiências aumentam o risco trombótico.\n\n**MTHFR** — Mutação que pode afetar o metabolismo do folato e homocisteína.\n\n### Como Interpretar\n\nSempre discuta os resultados com seu médico especialista. Um resultado alterado isolado não define o diagnóstico — o contexto clínico é fundamental.`,
  },
  {
    id: 'medicacao',
    title: 'Rotina de Medicação',
    subtitle: 'Organize e entenda suas medicações',
    icon: '💊',
    color: '#8B6F9E',
    premium: false,
    content: `## Guia de Rotina de Medicação\n\nO manejo medicamentoso na trombofilia durante a gestação é um dos pilares do cuidado. A adesão correta ao tratamento é essencial para a saúde da mãe e do bebê.\n\n### Enoxaparina (Heparina de Baixo Peso Molecular)\n\nA enoxaparina é o anticoagulante de escolha durante a gestação. É aplicada por via subcutânea, geralmente uma ou duas vezes ao dia.\n\n**Técnica de aplicação:**\n- Escolha o local de aplicação (abdômen, coxas ou braços)\n- Faça uma prega na pele com os dedos\n- Insira a agulha em ângulo de 90°\n- Injete lentamente o medicamento\n- Não massageie após a aplicação\n- Alterne os locais de aplicação\n\n**Importante:** Nunca interrompa a medicação sem orientação médica. Em caso de cirurgia ou parto, informe sempre sobre o uso de anticoagulantes.\n\n### Ácido Acetilsalicílico (AAS)\n\nFrequentemente utilizado em baixas doses (100mg) em conjunto com a heparina, especialmente na síndrome antifosfolípide.\n\n### Progesterona\n\nPode ser prescrita para suporte da fase lútea em casos de FIV ou histórico de perdas precoces.`,
  },
  {
    id: 'suplementacao',
    title: 'Suplementação Essencial',
    subtitle: 'Vitaminas e minerais importantes na gestação com trombofilia',
    icon: '🌿',
    color: '#6BAF8A',
    premium: false,
    content: `## Guia de Suplementação Essencial\n\nA suplementação adequada é parte fundamental do cuidado pré-concepcional e gestacional, especialmente para mulheres com trombofilia.\n\n### Ácido Fólico / Metilfolato\n\nFundamental para a prevenção de defeitos do tubo neural. Para mulheres com mutação MTHFR, o metilfolato (forma ativa) pode ser mais indicado que o ácido fólico convencional. A suplementação deve iniciar idealmente 3 meses antes da concepção.\n\n**Dose habitual:** 400mcg a 5mg/dia (conforme orientação médica)\n\n### Vitamina D\n\nDeficiência de vitamina D está associada a complicações gestacionais. A dosagem sérica deve ser avaliada e a suplementação individualizada.\n\n**Dose habitual:** 1.000 a 4.000 UI/dia (conforme níveis séricos)\n\n### Ômega-3\n\nTem propriedades anti-inflamatórias e pode auxiliar na saúde cardiovascular e placentária.\n\n### Ferro\n\nEssencial para prevenir anemia gestacional. Deve ser monitorado por exames periódicos.\n\n### Cálcio e Magnésio\n\nImportantes para saúde óssea e prevenção de cãibras gestacionais.\n\n### Vitamina B12\n\nEspecialmente importante para mulheres com MTHFR ou que seguem dieta vegetariana/vegana.`,
  },
  {
    id: 'alimentacao',
    title: 'Alimentação e Estilo de Vida',
    subtitle: 'Hábitos saudáveis para sua gestação',
    icon: '🥗',
    color: '#E8B86D',
    premium: false,
    content: `## Guia de Alimentação e Estilo de Vida\n\nUma alimentação equilibrada e hábitos saudáveis são aliados poderosos no manejo da trombofilia gestacional.\n\n### Alimentação Anti-inflamatória\n\nPriorize alimentos com propriedades anti-inflamatórias naturais:\n- Peixes ricos em ômega-3 (salmão, sardinha, atum)\n- Azeite de oliva extravirgem\n- Frutas vermelhas e roxas (ricas em antioxidantes)\n- Vegetais folhosos verde-escuros\n- Cúrcuma e gengibre\n- Nozes e sementes\n\n### Alimentos a Moderar\n\nAlimentos que podem aumentar a inflamação ou interferir na coagulação:\n- Alimentos ultraprocessados\n- Açúcar refinado em excesso\n- Gorduras trans\n- Álcool (contraindicado na gestação)\n\n### Vitamina K e Anticoagulantes\n\nSe você usa warfarina (pouco comum na gestação), a ingestão de vitamina K deve ser monitorada. Com heparina, não há restrição alimentar relacionada à vitamina K.\n\n### Hidratação\n\nBeber água adequadamente (cerca de 2 litros/dia) ajuda na circulação e reduz o risco de trombose.\n\n### Atividade Física\n\nA movimentação regular, mesmo que leve, é benéfica. Caminhadas, hidroginástica para gestantes e yoga pré-natal são excelentes opções. Sempre com liberação médica.\n\n### Posição e Circulação\n\nEvite ficar parada por longos períodos. Em viagens longas, use meias de compressão e movimente as pernas regularmente.`,
  },
  {
    id: 'parto',
    title: 'Parto com Trombofilia',
    subtitle: 'Planejamento e cuidados especiais para o parto',
    icon: '🏥',
    color: '#C9748F',
    premium: false,
    content: `## Guia de Parto com Trombofilia\n\nO planejamento do parto para mulheres com trombofilia requer atenção especial e comunicação clara com a equipe médica.\n\n### Planejamento Antecipado\n\nConverse com seu obstetra e hematologista sobre o plano de parto com antecedência. Defina:\n- Quando suspender a heparina antes do parto\n- Protocolo para anestesia peridural (geralmente requer suspensão da heparina por 12-24h antes)\n- Reinício da anticoagulação após o parto\n- Amamentação e anticoagulantes\n\n### Suspensão da Heparina\n\n**Heparina de baixo peso molecular:** Geralmente suspensa 24 horas antes do parto programado ou da peridural.\n\n**Heparina não fracionada:** Suspensa 4-6 horas antes.\n\nEm caso de trabalho de parto espontâneo, informe imediatamente a equipe sobre o uso de anticoagulantes.\n\n### Pós-parto\n\nO período pós-parto também requer anticoagulação, pois o risco trombótico permanece elevado. A heparina geralmente é reiniciada 6-12 horas após o parto vaginal e 12-24 horas após a cesárea.\n\n### Amamentação\n\nA heparina não passa para o leite materno em quantidades significativas e é considerada segura durante a amamentação. A warfarina também é compatível com a amamentação.`,
  },
  {
    id: 'acompanhamento_semanal',
    title: 'Acompanhamento por Semana',
    subtitle: 'Rotina de consultas e exames semana a semana',
    icon: '📅',
    color: '#7BB8D4',
    premium: false,
    content: `## Guia de Rotina de Acompanhamento da Gestação por Semana\n\n### 1º Trimestre (Semanas 1-13)\n\n**Semanas 4-8:** Confirmação da gestação, beta-HCG seriado, progesterona sérica, início do acompanhamento com hematologista.\n\n**Semanas 8-12:** Ultrassom de 1º trimestre (translucência nucal), doppler uterino precoce, exames laboratoriais completos.\n\n**Semana 11-13:** Rastreamento combinado de 1º trimestre (translucência nucal + bioquímica).\n\n### 2º Trimestre (Semanas 14-27)\n\n**Semanas 18-22:** Ultrassom morfológico de 2º trimestre, avaliação detalhada da anatomia fetal.\n\n**Semanas 20-24:** Doppler de artérias uterinas (rastreamento de pré-eclâmpsia), medida do colo uterino.\n\n**Semana 24-28:** Teste de tolerância à glicose (diabetes gestacional), hemograma, coagulograma.\n\n### 3º Trimestre (Semanas 28-40)\n\n**Semanas 28-32:** Ultrassom de crescimento fetal, doppler umbilical e cerebral.\n\n**Semanas 32-36:** Ultrassom de crescimento, perfil biofísico fetal, avaliação do líquido amniótico.\n\n**Semanas 36-40:** Preparação para o parto, discussão sobre suspensão da anticoagulação, plano de parto.`,
  },
  {
    id: 'avaliacao_complementar',
    title: 'Avaliação Geral Complementar',
    subtitle: 'Exames e avaliações complementares importantes',
    icon: '📋',
    color: '#8B6F9E',
    premium: false,
    content: `## Guia de Avaliação Geral Complementar\n\nAlém dos exames específicos para trombofilia, uma avaliação complementar abrangente é fundamental para o cuidado integral.\n\n### Avaliação Cardiológica\n\nMulheres com trombofilia, especialmente com SAF, podem ter maior risco cardiovascular. Uma avaliação cardiológica com ecocardiograma pode ser indicada.\n\n### Avaliação Reumatológica\n\nA síndrome antifosfolípide pode estar associada a doenças autoimunes como lúpus eritematoso sistêmico. Avaliação com reumatologista pode ser necessária.\n\n### Avaliação Neurológica\n\nHistórico de AVC, AIT ou trombose de seio venoso cerebral requer acompanhamento neurológico.\n\n### Exames de Imagem\n\nDoppler venoso de membros inferiores pode ser indicado em casos de histórico de TVP ou fatores de risco adicionais.\n\n### Densitometria Óssea\n\nUso prolongado de heparina pode afetar a densidade óssea. Avaliação pode ser indicada em tratamentos de longa duração.\n\n### Avaliação Psicológica\n\nO impacto emocional da trombofilia e das perdas gestacionais é significativo. O suporte psicológico é parte essencial do cuidado integral.`,
  },
  {
    id: 'dopplers',
    title: 'Entender Dopplers',
    subtitle: 'Compreenda os exames de doppler na gestação',
    icon: '📡',
    color: '#C9748F',
    premium: false,
    content: `## Guia para Entender Dopplers\n\nO exame de doppler é uma ferramenta fundamental no acompanhamento de gestações de alto risco, especialmente em mulheres com trombofilia.\n\n### O que é o Doppler?\n\nO doppler obstétrico avalia o fluxo sanguíneo nos vasos do útero, placenta e feto. Permite identificar alterações na circulação que podem indicar comprometimento fetal.\n\n### Principais Vasos Avaliados\n\n**Artérias Uterinas:** Avaliam a resistência vascular no útero. Índices elevados podem indicar risco aumentado de pré-eclâmpsia e restrição de crescimento fetal.\n\n**Artéria Umbilical:** Avalia o fluxo entre a placenta e o feto. Ausência ou reversão do fluxo diastólico é sinal de alerta grave.\n\n**Artéria Cerebral Média (ACM):** Avalia a redistribuição do fluxo sanguíneo fetal. O índice de pulsatilidade baixo pode indicar centralização fetal.\n\n**Ducto Venoso:** Avalia o fluxo venoso fetal. Alterações indicam comprometimento cardíaco fetal.\n\n### Índices Importantes\n\n- **IP (Índice de Pulsatilidade):** Mede a variação do fluxo\n- **IR (Índice de Resistência):** Mede a resistência vascular\n- **Relação S/D:** Razão entre fluxo sistólico e diastólico\n- **Relação CPR (Cerebro-Placentária):** Relação entre ACM e artéria umbilical`,
  },
  {
    id: 'trombofilias',
    title: 'Trombofilias Adquiridas e Anticorpos Antifosfolípides',
    subtitle: 'Entenda a síndrome antifosfolípide e trombofilias adquiridas',
    icon: '🔬',
    color: '#D4697A',
    premium: false,
    content: `## Guia sobre Trombofilias Adquiridas e Anticorpos Antifosfolípides\n\n### O que são Trombofilias?\n\nTrombofilias são condições que aumentam a tendência à formação de coágulos sanguíneos (trombos). Podem ser hereditárias (genéticas) ou adquiridas.\n\n### Síndrome Antifosfolípide (SAF)\n\nA SAF é a trombofilia adquirida mais importante na gestação. É uma doença autoimune caracterizada pela presença de anticorpos antifosfolípides e manifestações clínicas como trombose e/ou complicações obstétricas.\n\n**Critérios Diagnósticos (Sapporo/Sydney):**\n\nCritérios Clínicos:\n- Trombose vascular (arterial, venosa ou de pequenos vasos)\n- Morbidade gestacional (perdas fetais, pré-eclâmpsia grave, insuficiência placentária)\n\nCritérios Laboratoriais (pelo menos um, positivo em duas ocasiões com ≥12 semanas de intervalo):\n- Anticoagulante lúpico\n- Anticardiolipina IgG ou IgM (títulos médios/altos)\n- Anti-beta2-glicoproteína I IgG ou IgM\n\n### Trombofilias Hereditárias\n\n**Fator V de Leiden:** Mutação mais comum. Causa resistência à proteína C ativada.\n\n**Mutação da Protrombina G20210A:** Segunda mutação mais comum. Aumenta os níveis de protrombina.\n\n**Deficiência de Proteína C:** Proteína anticoagulante natural. Deficiência aumenta risco trombótico.\n\n**Deficiência de Proteína S:** Cofator da proteína C. Deficiência funcional ou quantitativa.\n\n**Deficiência de Antitrombina:** Inibidor mais potente da coagulação. Deficiência aumenta significativamente o risco.`,
  },
  {
    id: 'vencimento_medicacoes',
    title: 'Vencimento e Controle de Medicações',
    subtitle: 'Organize e controle suas medicações',
    icon: '⏰',
    color: '#E8B86D',
    premium: false,
    content: `## Guia de Vencimento e Controle de Medicações\n\nO controle adequado das medicações é essencial para a segurança do tratamento da trombofilia.\n\n### Organização das Medicações\n\n**Verificação de Validade:**\nSempre verifique a data de validade antes de usar qualquer medicamento. Medicamentos vencidos devem ser descartados adequadamente em farmácias ou postos de saúde.\n\n**Armazenamento:**\n- Heparina/Enoxaparina: temperatura ambiente (15-30°C), protegida da luz\n- Evite locais úmidos (banheiro) ou com variação de temperatura\n- Mantenha fora do alcance de crianças\n\n### Controle de Estoque\n\nMantenha sempre um estoque de segurança de pelo menos 7 dias de medicação. Solicite renovação da receita com antecedência.\n\n### Descarte Correto\n\nAgulhas e seringas usadas devem ser descartadas em recipiente rígido (coletor de perfurocortantes). Nunca descarte no lixo comum.\n\n### Viagens\n\nAo viajar, leve medicação suficiente para todo o período mais uma reserva. Transporte em bagagem de mão com receita médica e laudo em inglês se for ao exterior.\n\n### Substituição de Marcas\n\nNunca substitua a marca da heparina sem orientação médica. Diferentes marcas podem ter biodisponibilidades distintas.`,
  },
  {
    id: 'plano_parto',
    title: 'Plano de Parto Digital',
    subtitle: 'Crie e compartilhe seu plano de parto personalizado',
    icon: '📝',
    color: '#8B6F9E',
    premium: true,
    content: `## Plano de Parto Digital\n\nO plano de parto é um documento que expressa seus desejos e preferências para o momento do parto. Para mulheres com trombofilia, ele tem particularidades importantes.\n\n### Informações Essenciais para Incluir\n\n**Dados Médicos:**\n- Diagnóstico de trombofilia (tipo específico)\n- Medicações em uso (especialmente anticoagulantes)\n- Data da última dose de heparina\n- Alergias medicamentosas\n- Nome e contato do hematologista/obstetra\n\n**Preferências para o Parto:**\n- Tipo de parto desejado (normal/cesárea)\n- Preferências sobre analgesia/anestesia\n- Acompanhante desejado\n- Clampeamento do cordão\n- Contato pele a pele\n- Amamentação na sala de parto\n\n**Pós-parto:**\n- Reinício da anticoagulação\n- Amamentação\n- Cuidados com o recém-nascido\n\n### Como Usar este Guia\n\nPreencha as informações no formulário de Plano de Parto Digital disponível na área de recursos do aplicativo. Você poderá salvar, imprimir e compartilhar com sua equipe médica.`,
  },
];

export const QUICK_ACTIONS = [
  { id: 'medication', label: 'Medicações', icon: '💊', route: '/journey/medications' },
  { id: 'exams', label: 'Exames', icon: '🧪', route: '/journey/exams' },
  { id: 'diary', label: 'Diário', icon: '📖', route: '/journey/diary' },
  { id: 'timeline', label: 'Linha do Tempo', icon: '📅', route: '/journey/timeline' },
  { id: 'symptoms', label: 'Sintomas', icon: '🌡️', route: '/journey/symptoms' },
  { id: 'doppler', label: 'Dopplers', icon: '📡', route: '/journey/dopplers' },
];

export const COMMUNITY_POSTS = [
  {
    id: '1',
    author: 'Ana Paula',
    avatar: '👩',
    time: '2h atrás',
    content: 'Hoje completei 28 semanas! Quem diria que chegaria até aqui depois de 3 perdas. A enoxaparina foi minha companheira fiel. Gratidão a todas que me apoiaram nessa jornada! 💜',
    likes: 47,
    comments: 12,
    type: 'relato',
  },
  {
    id: '2',
    author: 'Mariana Costa',
    avatar: '👩‍🦱',
    time: '5h atrás',
    content: 'Dúvida: alguém já teve que ajustar a dose de enoxaparina no 3º trimestre? Minha médica está considerando aumentar e fiquei um pouco apreensiva.',
    likes: 23,
    comments: 18,
    type: 'duvida',
  },
  {
    id: '3',
    author: 'Fernanda Lima',
    avatar: '👩‍🦰',
    time: '1d atrás',
    content: '🌈 Mural de Nascimentos: Apresentando minha filha Sofia, nascida com 38 semanas, saudável e linda! Após SAF diagnosticada e 2 perdas, ela é nosso arco-íris. Obrigada a todas!',
    likes: 156,
    comments: 43,
    type: 'nascimento',
  },
];

export const FIV_PHASES = [
  { id: 'estimulacao', label: 'Estimulação Ovariana', icon: '💉', color: '#7BB8D4', description: 'Injeções hormonais para estimular os ovários' },
  { id: 'monitorizacao', label: 'Monitorização', icon: '🔍', color: '#8B6F9E', description: 'Ultrassons e exames para acompanhar os folículos' },
  { id: 'puncao', label: 'Punção dos Óvulos', icon: '🔬', color: '#C9748F', description: 'Coleta dos óvulos para fertilização' },
  { id: 'fertilizacao', label: 'Fertilização', icon: '⚗️', color: '#6BAF8A', description: 'Fertilização dos óvulos em laboratório' },
  { id: 'cultivo', label: 'Cultivo Embrionário', icon: '🧬', color: '#E8B86D', description: 'Desenvolvimento dos embriões' },
  { id: 'transferencia', label: 'Transferência', icon: '💜', color: '#9B7EC8', description: 'Transferência do embrião para o útero' },
  { id: 'espera', label: 'Espera do Beta-HCG', icon: '⏳', color: '#D4697A', description: 'Aguardando o resultado do teste de gravidez' },
  { id: 'resultado', label: 'Resultado', icon: '🌟', color: '#C9748F', description: 'Beta-HCG positivo ou negativo' },
];

export const WEEK_MILESTONES: Record<number, string> = {
  4: 'Implantação do embrião',
  6: 'Coração começa a bater',
  8: 'Órgãos principais em formação',
  10: 'Feto com 3cm, movimentos iniciais',
  12: 'Fim do 1º trimestre',
  16: 'Possível sentir os primeiros movimentos',
  20: 'Ultrassom morfológico',
  24: 'Viabilidade fetal',
  28: 'Início do 3º trimestre',
  32: 'Pulmões em maturação',
  36: 'Bebê quase pronto',
  37: 'Gestação a termo',
  40: 'Data provável do parto',
};
